### ISSUE TITLE
As Poppy, I need to be able to contact my county clerk on "Register Trade Name" Task screen

### ISSUE THREAD

**Issue by Jesslax** [newjersey/business.nj.gov#117]
Activities Include:

- When Poppy selects either Sole Proprietorship or General Partnership AND selects a location in the onboarding, in the task "Register Trade Name" add the CTA link for the County Clerk, in the destination include the County Clerk contact information.

**Comment by aloverso** [comment]
@Jesslax does this mean the [Comply with Local Laws task](https://dev.d3v9e9ms5ulsh2.amplifyapp.com/tasks/check-local-requirements) and if so, don't we already have this link for the county clerk?

**Comment by aloverso** [comment]
@skeeJay @Jesslax This wasn't 100% clear as to how/where we wanted this content added, but I added a section to the best of my interpretation. But since it's in the task content files, feel free to make changes or update as needed

Or, if I misinterpreted, and there's different work to be done, do let me know!

**Comment by Jesslax** [comment]
@aloverso we talked about this last week and identified that I could make the edit myself. Basically I adding the county clerk's as links in the CTA for the trade name task.  I made that edit earlier this week. Can you show me what you edited on standup?

**Comment by aloverso** [comment]
@Jesslax Oh I see. I thought it still needed to be done because it was in the to-do column. I interpreted as including the county clerk info in the text as well

![image](https://user-images.githubusercontent.com/6563663/126558523-236e67e2-5881-4dca-a57c-8a8f5009f4b0.png)

If that's incorrect, I can remove it. Either way, we should close out the story if it's finished

**Comment by skeeJay** [comment]
I am not sure where the breakdown happened, but I'll take responsibility for not calling more attention to this during standups. Apologies if this created unnecessary work for you, @aloverso. @Jesslax, and can you compare your prior change, and Anne's change, and rectify them/see which solution you like better, reduce any redundancies, and if it looks like the work is complete, let us know this can be marked complete?

**Comment by skeeJay** [comment]
@Jesslax Are you able to take a final look at this so @aloverso can deploy?

**Comment by Jesslax** [comment]
@skeeJay meeting with Guy now, will message once complete.

**Comment by Jesslax** [comment]
@skeeJay @aloverso All set.
