### ISSUE TITLE
Update Task ID names and scenario when displayed

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#146]
Activities include:

- [x] - Swap out the “identify-potential-lease” task in the roadmap with "check-site-suitability" task
- [x] - Once you do the above, you will have "check site-suitability" twice in the roadmap, delete the one with a higher weight.
- [x] - Change ID name from "identify-potential-lease" to "evaluate- site"
- [x] - Change ID name from "check-site-suitability" to "evaluate-site-cosmetology"  
- [ ] - Display "fire-permit" in roadmap only when Cosmetology industry is selected  
- [x] - Display "certificate-of-occupancy" in roadmap when Cosmetology is NOT selected AND home-based business selected 'No'
- [x] - Change ID name from "fire-permit" to "certificate-of-occupancy-cosmetology"
- [x] - Display "building-permit" if they are not a home-based business. Since cosmo and restaurants are always not a home-based businesses, always display them for those industries.
- [x] - Change ID name from "research-insurance-needs" to "get-insurance" 
- [ ] - Change ID name from "liquor-license-obtain" to "comply-local-requirements-liquor"
- [ ] - When liquor license is selected, remove "check-local-requirements" (because it is now being replaced by "comply-local-requirements-liquor")

### Dev notes

- [x] add urlSlugs to tasks that are different from ids
- [x] allow filenames to be different from ids
- [x] decide whether to use filenames or ids or urlSlugs in the roadmap-building jsons
- [x] make it clear that FILENAMES not IDs are used in the roadmap-building JSON
- [ ] decide if we want to pitch a UI for this

**Comment by skeeJay** [comment]
@Jesslax I don't totally understand the new name of this story. If it's an engineering story for Anne, can we reformat with "As Poppy" as a user story? That might help clarify.

**Comment by Jesslax** [comment]
@skeeJay as I've been working through the copy I have made updates to certain tasks, and as a result tasks need to be relocated to different places than where they used to be. These relocations occur under different situations. I could try and name it as Poppy, I need an accurate roadmap. 

I also renamed a handful of the tasks, so now the task ID and the task title is very different and it can be hard to know what task relates to what ID. So I want to rename certain tasks. I could separate these and make it a separate ticket, calling this one  as Jessica I need task IDs that are similar to their task title.

I grouped them together because I saw them as minor engineering edits. Let me know the best way to do this.

**Comment by aloverso** [comment]
@Jesslax when you're back online, we made several changes to the task-ID and file names structure to make it easier to for these to be managed and used going forward. We should find time to talk through and see if there's anything else you might want/need

**Comment by Jesslax** [comment]
@aloverso Thank you! Seems like a lot of the task-IDs have been renamed for the better, awesome. I'll put time on the calendar for tomorrow.

**Comment by Jesslax** [comment]
@aloverso was reviewing this checklist at the top, and I am not seeing some of these changes, maybe we can check-in again tomorrow, because I think it's just a knowledge gap on my side. 

While I understand how I can change everything myself now, because some items were changed while I was away, it's not clear what the old names were and what the new names are. So for example, in the activities listed above we have an item that says "Change ID name from "fire-permit" to "certificate-of-occupancy-cosmetology" but I don't see either of those task name listed [here ](https://github.com/newjersey/business.nj.gov/tree/main/web/roadmaps/tasks) now, so I am not sure how to check if these activities were completed.

**Comment by aloverso** [comment]
@Jesslax I also struggled with this because some of them had already been changed before I picked up this story. For that one, "fire-permit" had already been deleted as a task but I did try to go through them all to find the tasks I was pretty sure that you were referencing (in this case, `site-safety-permits-cosmetology`)

I did rename a few of the files, like that one, mostly to demo/test that it was now possible. 

To be honest, I think that some of the checklist items above are very out of date (you wrote that list on June 9) so it might be easier/preferable for us to go through the roadmap and compare against your spreadsheets / master doc and look for discrepancies instead of trying to interpret what the checklist items reference

**Comment by Jesslax** [comment]
@aloverso All good, I will re-immerse myself then. Might take me until the end of the week to double check this.

**Comment by skeeJay** [comment]
@Jesslax Just re-upping it.

**Comment by Jesslax** [comment]
@skeeJay This is going to take a fair amount of time for me to look into, I honestly don't know if I can get to it this week. If we want, we can close it, and I can create a new ticket if anything else needs to be done. This would be my suggestion.

**Comment by skeeJay** [comment]
@Jesslax Yes I think that's what we should do at this point. Okay, thanks.
