### ISSUE TITLE
License Task screen QA

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#158]
Activities include:

- [ ]

# QA

For #134 

- [x] In design, there is larger padding in the white checklist area below the last checklist item.
- [x] In design, the "pending" clock icon has lower weight, both in individual checklist items and in top "Permit Status" bar.

**Comment by aloverso** [comment]
@skeeJay Talked with @guy-nj about the clock icon, he used a different one in the designs than what's available in USWDS, so I think we can remove that item from the qa checklist. Otherwise, other fix is ready

**Comment by skeeJay** [comment]
Hmm. From my perspective, that introduces a problem, which is that the USWDS version doesn’t provide as nice a weight-and-thickness difference from the checkmark like we all liked in the design review. @guy-nj do you think there are any options or alternatives that would bring back that different in weight and thickness?

**Comment by guy-nj** [comment]
A solution I can think of is to host the icon by ourselves, which we might need to do sooner or later. @aloverso is that something we can do and what icon format you will need from me?

**Comment by aloverso** [comment]
Per what @guy-nj suggested, I updated the color to be lighter to compensate for the difference.
As for hosting our own icons, I'm not sure. I know we're not allowed to modify any of the USWDS icons [per their license](https://github.com/uswds/uswds/blob/develop/LICENSE.md), but you're suggesting adding our own self-created icons, right? I don't think that'd be an issue, but it should be a separate story because there'd be technical complexity in changing the way that the icons are loaded onto the page, since right now the code assumes we're using the USWDS system

**Comment by guy-nj** [comment]
Yes I meant self-created icons. We can keep this USWDS icon for now. When the day comes that we really need to use our own icons, we can revisit this altogether?

**Comment by skeeJay** [comment]
I think lightening the icon is a totally valid solution.

**Comment by skeeJay** [comment]
These look great. I think the lighter opacity makes the distinction between the two icons much more scannable.
