### ISSUE TITLE
As Poppy, I need to see a task linking to my municipality's requirements in my roadmap

### ISSUE THREAD

**Issue by skeeJay** [newjersey/business.nj.gov#25]
Activities include:

- [ ]

**Comment by dltinnovate** [comment]
Roadmap: Step 4 Task 2

Activities Include:

1. Display instructions and content for users
- Description Text
- Will Need
- Will Get

2. Display the town selected during onboarding
3. Link Users to the local municipal website of the town they selected during onboarding

[This document](https://docs.google.com/document/d/1pXNg4Zndd1EuWYfUv9ep38CTSYTozIvwJipSkiT_yrY/edit?usp=sharing) contains the Task Screen, Roadmap View, all text, and Potential Contextual Information.

[Airtable with list of Municipalities and their Websites](https://airtable.com/invite/l?inviteId=invBOQXzyIMg9K6Mm&inviteToken=b2f62f141c99f445876c36aa0b4cd3384abcd5bc70e1feee1d514d5a226c9ba6)

**Comment by aloverso** [comment]
@skeeJay @dltinnovate @Jesslax when does this task show up on the roadmap?

Is it only on their roadmap if they have selected a municipality? (and then we link them to the correct website)

Or do we show the task always, but not show them a link unless they've selected a municipality?

If we don't care, I will say the first option is easier to do

**Comment by aloverso** [comment]
A few additional thoughts:
- what links do we want on the page? right now the button links to the town website, but we also have access to the following data: county website, county clerk webpage, county clerk phone number
- right now, the task completion status is independent of _which_ town you selected. This means that if I select "Alexandria Township" and mark the task as completed because I talked to the Alexandria county clerk and all, and then I later edit my data and switch municipality to "Franklin Township", the task will remain in its completed state (although the text inside it will switch to link to Franklin Township instead). If we want to change this, that's fine, but we should maybe add another story for it.

**Comment by dltinnovate** [comment]
> @skeeJay @dltinnovate @Jesslax when does this task show up on the roadmap?
> 
> Is it only on their roadmap if they have selected a municipality? (and then we link them to the correct website)
> 
> Or do we show the task always, but not show them a link unless they've selected a municipality?

I think the best situation is to show them the "to-dos" no matter what. The information/requirements are relevant for every town. However, we might want to modify this page for home-based business since most of the tasks don't apply. Maybe we should make a separate story for that @Jesslax, but I'm not sure it's needed for this first iteration.

**Comment by Jesslax** [comment]
@aloverso 
1) That's a great point, and we should make another story for folks changing towns.
2) I think we require folks to select a municipality, and then link out to their specific county clerk information.  (So people can't finish onboarding unless they pick a municipality). If we don't want to do that for some reason, I agree with Joe.
3) As Joe said, if folks click home-based businesses, we might want to put different information in the task, but link out to the same spot. Not sure if we already have a story for this.
4) I believe we link out to county clerk website, but probably would be great to have phone number listed too, what do you think @dltinnovate

**Comment by aloverso** [comment]
@Jesslax @dltinnovate that makes sense. check out the current version (live on the dev site). I made the change Joe suggested so that the task is always visible, and if you select a municipality then it will show you the link to the town website

**Comment by skeeJay** [comment]
Looks to work as expected, but @dltinnovate you may want to spot check several municipalities.

I am realizing that in almost any situation with a green button linking to an "external" website, we should probably open a new tab. Let me know if anyone disagrees, but I think that would be the expected and ideal behavior when taking someone to an external site. @aloverso because that would need to be implemented across Task screens at this point, should it maybe be its own user story?

**Comment by dltinnovate** [comment]
I've updated the Air Table to clarify a few entries. The spot checks looked good. @Jesslax I agree. It couldn't hurt to include the county clerk phone number. @skeeJay agree, it would be better to have the link out open in a new tab.

**Comment by skeeJay** [comment]
@dltinnovate Where did we leave the inclusion of the county clerk phone number? Is that getting written up as a new user story?
