### ISSUE TITLE
Navbar bug - fix padding & vertical line alignment

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#303]
Looks like #220 introduced two visual design bugs:

## extra padding in between the navbar and page content 

(see before & after below)

![image](https://user-images.githubusercontent.com/6563663/130822565-446268e6-d64d-42fe-a8af-234a913a73a1.png)

## misaligned vertical lines on the mobile mini-roadmap in sidebar 

(see after & before below)

![image](https://user-images.githubusercontent.com/6563663/130851318-0684b0ef-cb87-4976-9a48-67b3e436edf5.png)

**Comment by aloverso** [comment]
@carye3 as I was adding the bug report for this one, I also noticed the padding change displayed above. wanted to confirm that the padding change is also a bug to be fixed?

**Comment by carye3** [comment]
@FarazA22 just getting caught up. Does this need design support?

**Comment by skeeJay** [comment]
@carye3 Want to QA with a design eye? cc @kmelefsky

**Comment by carye3** [comment]
We addressed this last week correct @FarazA22 ?

**Comment by FarazA22** [comment]
@carye3 The two bugs appeared as a result of some changes I made to styling. The whitespace around the 'back to roadmap' button was discussed last week and comments were left in Figma.  The vertical line issue was not discussed since the styling changes caused a deviation from design; the UI was corrected to reflect design.
