### ISSUE TITLE
Inconsistent state as landing page is loading

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#486]
When the landing page is first loading and determining if the user is already signed-in or not, the "Log in" buttons do not display consistent state

The button in the navbar will show "Log in" and the button in the body of the page will show "Log out"

**Comment by aloverso** [comment]
![Screen Shot 2021-09-20 at 10 49 40 AM](https://user-images.githubusercontent.com/6563663/134023174-8b8da111-b396-4018-86cf-5dcbadca0ae9.png)

**Comment by skeeJay** [comment]
@carye3 will let you QA from a design perspective. One think I noticed as a regression: when the dropdown opens, the location of the current status "jumps" to the right because the dropdown that appears is no longer "perfectly" aligned with the the button that opens it. I don't know if we care about that, but it's something that I think we implemented in the old location.

**Comment by skeeJay** [comment]
@aloverso I still see these buttons disagree as I am getting redirected on dev.

**Comment by aloverso** [comment]
@skeeJay i think this is fixed now?

**Comment by skeeJay** [comment]
@aloverso I now see them both flash as "Log In," both simultaneously flash to "Log Out," and then the whole page redirects to the Roadmap. I think that's the expected behavior, yeah?

**Comment by aloverso** [comment]
Yes, that's what I would expect, to keep them consistent at least. If you want it to be different though, we can change it
