### ISSUE TITLE
As Poppy, I need to "unofficially" see if my business name already exists from a Task screen, and then be linked to the official tool

### ISSUE THREAD

**Issue by dhcole** [newjersey/business.nj.gov#5]
**Design**
[Laptop](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2123%3A5&viewport=-3997%2C64%2C0.11922770738601685&scaling=min-zoom) 
[Mobile](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=488%3A3970&node-id=2134%3A29642&viewport=641%2C706%2C0.19513079524040222&scaling=min-zoom) (1 screen only)

**User Actions**
As Poppy, 
- [x] I see my previously input name during the onboarding flow being pre-populated in the field.
- [x] If my desired name is taken, there is a message communicating the name being not available; and showing up to 10 similar taken names (to further discuss @Jesslax @skeeJay @aloverso)
- [x] The error message stays until the user click on "Check Availability" again.
- [x] If my desired name is available, there is a message communicating the name "likely" being available, and a notification box prompting the user to do an official check at Treasury website. I see a button "Official Name Check" (Copy TBD) which brings me to the Treasury website in a new tab.
- [x] If my desired name is available, I can update the name in the roadmap UI by clicking "Update the name on your roadmap with this one" (copy TBD). After I click it, the link changes to a checkmark and text "Your business name has been updated." (copy TBD). [See design](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2123%3A168&viewport=-1997%2C227%2C0.06432311981916428&scaling=min-zoom).
- [x] I see a loading icon (@aloverso let's use the [default Material UI styling](https://next.material-ui.com/components/buttons/#loading-buttons)? ) in the button so I know the search being performed and the button is disabled. I see my search term included in the results messaging. Then the search results go away when the "Search Availability" is clicked again. [See design](https://www.figma.com/proto/Hg3ggwTj50wxdg4mjG4xRB/Dashboard-Exploration?page-id=0%3A1&node-id=2123%3A5&viewport=-10622%2C92%2C0.24056360125541687&scaling=min-zoom)

**Comment by aloverso** [comment]
@skeeJay @guy-nj should we show the "update my name in roadmap..." button only if the name is actually different from their current saved name?

**Comment by guy-nj** [comment]
@aloverso @skeeJay I have added the design for after clicking "Update the name on your roadmap with this one". The copy is TBD. Please let me know if anything is still missing.

**Comment by aloverso** [comment]
@skeeJay @guy-nj not "ready for QA" fully yet but I wanted to let you know a first-pass version is live on the dev site in case you wanted to take a look ahead of time. since this is a big story with a lot of work, I thought it might help to give you a chance to look before it's fully "finished" so we can talk over some pieces

Here's some notes:

1. Since we're still pending the AWS story, it is not yet searching on the full set of business names from Treasury, just a subset. The connection to Treasury via Boomi is live, I've just limited it to about 100 names for now. Fun hack to see the whole list of names we have is if you just type a space into the textbox and search it. (or better yet, leave the textbox empty and search!)
2. Speaking of that hack, should we do any checks on the user's input before searching it?
2. @skeeJay I wasn't sure what matching algorithm we want to be using. Right now it's almost definitely incorrect - it just checks if your business name is "contained within" the existing name. So "Rink" is be unavailable because it is contained within "Brinker Restaurant". We should discuss how we actually want these
3. @guy-nj Similar to the feedback on the Update button, do we want some feedback that it performs a search? For example, if you type an available name, then type a different name and click "Check Availability" it's available, the screen doesn't change so the user might be worried it didn't actually do the second search. 
4. How do we want to handle cleaning up the Treasury data? For example, search "Boundaries" to see some weird quote marks and spacing. 
5. Speaking of cleanup, should we handle/display suffixes of existing businesses? All of the "LLC" and "INC" and "A LIMITED DIVIDEND HOUSING PARTNERSHIP" that are attached to all these names. 

Here's what I know for sure still needs to be done, let me know if you have more:
- [ ] Guy's design for when "update my name in roadmap" is clicked
- [ ] A lot of tech cleanup (database migrations for AWS)
- [ ] limiting the list of similar names to 10 elements only

**Comment by skeeJay** [comment]
@aloverso Cooooool. Noted on all counts, will take a look.

**Comment by guy-nj** [comment]
@aloverso Good catch. I have added designs for the visual feedback on "Search Availability" button. The note and design have been added to the User Actions above.

**Comment by skeeJay** [comment]
@aloverso I imagine there may be things that will change and things we want to tweak after that, so I won't really run down a list of things I notice right now. For example, the search field resets when you change the status of the Task, which is a little unexpected.

@guy-nj @aloverso @Jesslax One thing that occurs to me is that we may _not_ want to remove things like quotes or extraneous spaces from business name query results. Our tool may be a good way to expose the "uncleanliness" of the State's database. However, if we do this, way may want to give the search results a more "clinical" look/font so that it's clear this the "machine-speak" being read from the State's database verbatim. Just one potential avenue for discussion, though I'm by no means sure of it.

**Comment by aloverso** [comment]
@skeeJay oh good catch, we can fix that.

In general I think the most important question to answer, to get it into a more "ready" state, is about *how* we're doing our matching algorithm. If you have guidance on that

**Comment by aloverso** [comment]
@guy-nj thanks, I checked out the updated design. I have 2 questions:

1. Regarding the button state: do we really not want people to be able to perform the same search twice? Or to make them change their search query and then change it back in order to perform a search twice if they wanted? It's feasible from a tech perspective of course, but it's development effort to do it, and what problem are we solving by preventing that?
2. I'm not sure this addresses my concern about the search-results feedback. Maybe it's not actually a problem and I'm just assuming, but here's what I'm feeling. If I type a name like "anne's cool business" and search it, it comes back as available. And then if I change it to "anne's awesome business" and search it, it performs a search, but as the user I don't know it because the text still just says Available. At some point, that text represents the new results, but I don't know if that happened after 0.5 seconds or after 5 seconds. My question is, should we have some indication that a new search was performed? Like, removing the results text when they do a new search, showing a loading indicator, and then having it re-appear? Or even just showing the business name "Anne's awesome business is available" in the text so that they know that it searched on my new query? Not sure. But this is something I noticed and hard a hard time with even just as me, testing it

**Comment by guy-nj** [comment]
@aloverso Thanks for the suggestions. Please ignore my previous design.

1. We definitely need a spinner/loading-indicator on the search button for scenarios like this. Should we add the spinner to all buttons, or we can selectively add it for particular buttons?
2. Removing the previous search results seems solving the search-results feedback issue. I am on the fence of removing the search results when a) there is any change made in the previous search term, or b) when "Search Availability" is clicked again?
3. Pros/Cons for the two options above: 2a is visually clear indicating that "you are going to perform a new search". But does the user want to see the previous results for a big longer before the next search? My guess is it doesn't matter. 2b totally relies on the spinner to indicate the next search being performed. If the results return fast, the user might not even notice the new search being done and it runs into the same issue. 

Thoughts? And thanks again for thinking through this scenarios step by step. This is awesome.

**Comment by aloverso** [comment]
@guy-nj we can definitely add a button spinner, and it's not hard to add it selectively. Check out [the material UI button spinners](https://next.material-ui.com/components/buttons/#loading-buttons) to see some different loading states

Personally, I think I'd lean towards 2b, but you make a good point about whether it's a fast search or not. Right now it's performing the search in under 100ms, but that will almost certainly get larger when we increase to the full dataset, and also if we change the way we're talking to the Treasury data (Ross and I are currently discussing options)

**Comment by aloverso** [comment]
@skeeJay new matching rules are live on dev

**Comment by skeeJay** [comment]
@aloverso Thanks. We can talk about it on standup, but a couple of questions I'll have are:

1. Is there still a hack to see all names?
2. What's a good existing name to show already exists?
3. There are a couple edge cases I am noticing, like submitting a blank field says it exists, and just submitting "LLC" says it exists, and we probably need to figure out how to provide a third "error" message for both those cases.

**Comment by aloverso** [comment]
@skeeJay added the error message, I think that's all the items for this story?

**Comment by skeeJay** [comment]
@Jesslax @aloverso Let me know your thoughts, but my inclination was to make the third status type a more "forgiving"-looking error, since I think it's likely people may get it frequently putting in a term like `Incorporated` or `Company`. So I was thinking something more along the lines of the same font size and presentation as "Success" or "Already Taken" text (just with an orange font color, instead of green or red) instead of an error-style box.

But obviously curious to hear your thoughts. I only see this as a temporary solution anyway, because there's fair amount Guy could design or we could tailor further. For example, leaving it blank is more of a real user error than putting in "Company" and gently being told to get more specific.

So curious to hear what you think about a more forgiving treatment of the third result type for the time being. But either way, I'd clarify the text a little bit. Perhaps something like, "Sorry, that isn't a valid company name. Try being more specific."

**Comment by aloverso** [comment]
@skeeJay The copy itself is really easily changeable-by-Jess (or you) (same with all the text on the page) so I don't think that should be a blocker on marking the story completed. 

Re the visual treatment, that starts to sound like a larger conversation that we should loop @guy-nj into for discussing something that we want more long-term?

**Comment by skeeJay** [comment]
@aloverso I'm happy to leave it in either visual presentation for the short term; for the short term I just figured sticking with the visual presentation of text-only was actually sticking even closer to Guy's current designs. If we're going to leave a box with an icon, is there any way we can vertically align the icon with the text?

@Jesslax Can we update the text to something more friendly for the short term? I was thinking "Sorry, that isn't a valid company name. Try being more specific." but LMK what you think.

**Comment by Jesslax** [comment]
@skeeJay I updated it, I think that's fine for now. Remind me, were you saying you wanted two different error messages? Or you were saying that in either situation the error message will be due to lack of specificity? If we can regroup on that again, I'll try to think of the best way to communicate.

**Comment by skeeJay** [comment]
@Jesslax Thanks. I meant the latter; one message for everything. Trying to keep it as simple as possible for now. No point overthinking it until we do it proper.

**Comment by skeeJay** [comment]
@Jesslax Actually, I think you changed unavailableText, not badInputAlertText. I reverted that changed and updated the other one. It was the new error message that I wanted to expand on a bit.

I think this now meets all our original criteria, and that further changes should probably be new stories. I'll mark it Ready to Deploy unless anyone objects.

**Comment by Jesslax** [comment]
@skeeJay Got it. Now that you point out out that there is both unavailableText and badInputAlertText, that's what I meant by two different error messages - realizing you're thinking of them differently. I wonder if we can get even more specific with the messaging for badInputAlertText, but need to understand that better. For the demo, it's fine as is!
