### ISSUE TITLE
Protect the non-landing-page pages for non-authenticated users

### ISSUE THREAD

**Issue by aloverso** [newjersey/business.nj.gov#62]
Activities include:

- [x] when not authenticated, user cannot access Tasks page
- [x] when not authenticated, user cannot access Onboarding page
- [x] when not authenticated, user cannot access Roadmap page

**Comment by skeeJay** [comment]
@aloverso I do see a flash of the page I'm trying to get to, even if I'm not logged in at all, I imagine because by logged in state is being checked client-side. I guess the question becomes, is that satisfactory for us? Certainly an enterprising user of the browser could access the content via various tools, if they are not logged in. Do we care about that?
