### ISSUE TITLE
Franchise Page Content

### ISSUE THREAD

**Issue by CeciliaRam** [newjersey/business.nj.gov#906]
Content from the FAQ pages that needed rewriting to make a brand new section under Start (business.nj)

**Comment by CeciliaRam** [comment]
@Jesslax content is ready for review
https://docs.google.com/document/d/1vfb3Ew4Aed4-0XxKe9fG_pPANrk7IK1XAoEWMGjpmIM/edit#

**Comment by Jesslax** [comment]
@CeciliaRam Looking good, a few things:

1)Please start with a definition of a franchise rather than franchising. 
2) We need to check with Don: 
- businesses that are starting a franchise, what are they usually looking to find out?
- is there any special process for opening a franchise business
- if the state doesn't regulate franchises, what does that mean for business owners?
- does this belong on plan or start?
3)Add one sentence on who the International Franchise Association group is, and how they help prospective businesses.
